### PR TITLE
spring data is not necessary

### PR DESCRIPTION
**Pull request by m-masataka**
Signed-off-by: Masataka Mizukoshi <m.mizukoshi.wakuwaku@gmail.com>
I think ``springdata`` is not necessary in go impl.

If it is not true, we need to change name in ``ConfigurationStruct``.

### CODE REVIEW

**Comment by trcox** [comment]
Agreed, Masataka. I'll propagate the fix through the 3 core service go implementations, these were direct conversions from the Java side.

**Comment by spencerbull** [comment]
All of the keys in the [json files](https://github.com/edgexfoundry/core-metadata-go/tree/master/res) need to be updated to reflect the following [struct](https://github.com/edgexfoundry/core-metadata-go/blob/master/const.go#L23-L56)

Merging the current code would still result in consul improperly being configured.

**Comment by m-masataka** [comment]
@trcox  @bullapse thanks for reply.
Ok, I see. So should we wait until the core services come up?

**Comment by spencerbull** [comment]
Yes. I opened #11 to reflect the changes that need to be made to the configuration json.

**Comment by m-masataka** [comment]
I see. thanks for open #11

**Comment by spencerbull** [comment]
np. Working on a good configurations json now.

**Pull request closed without merging**
